import type { LegalDoc } from "./types";

export const TERMS_OF_SERVICE: LegalDoc = {
  "title": "AIRfasting Terms of Service",
  "version": "Version: Draft v1.0",
  "lastUpdated": "Last updated: 29 July 2026",
  "blocks": [
    {
      "type": "p",
      "text": "Service Operator: Jovere Collective S.L., a company incorporated in Spain (\"Jovere Collective,\" \"AIRfasting,\" \"we,\" \"us,\" or \"our\")"
    },
    {
      "type": "h1",
      "text": "1. Introduction"
    },
    {
      "type": "p",
      "text": "Welcome to AIRfasting, a digital wellness platform designed to help you plan, manage, and understand fasting in harmony with your body's natural rhythms. AIRfasting is operated by Jovere Collective S.L., a company registered in Spain."
    },
    {
      "type": "p",
      "text": "These Terms of Service (\"Terms\") form a binding agreement between you (\"you,\" \"User\") and Jovere Collective S.L. governing your access to and use of the AIRfasting website, applications, and related services (collectively, the \"Service\")."
    },
    {
      "type": "p",
      "text": "By creating an account or otherwise using AIRfasting, you agree to these Terms. If you do not agree, please do not use the Service."
    },
    {
      "type": "p",
      "text": "These Terms should be read together with our:"
    },
    {
      "type": "ul",
      "items": [
        "Privacy Policy",
        "Cookie Policy",
        "Health & Wellness Disclaimer"
      ]
    },
    {
      "type": "p",
      "text": "together, the \"Legal Framework.\" In the event of a direct conflict, these Terms govern matters of contract and use, while the Privacy Policy governs matters of personal data processing."
    },
    {
      "type": "h1",
      "text": "2. Who We Are"
    },
    {
      "type": "p",
      "text": "AIRfasting is operated by:"
    },
    {
      "type": "p",
      "text": "Jovere Collective S.L."
    },
    {
      "type": "p",
      "text": "Calle Quevedo, Núm. 16, 03700 Dénia (Alicante), Spain"
    },
    {
      "type": "p",
      "text": "NIF: B88998448"
    },
    {
      "type": "p",
      "text": "Spain"
    },
    {
      "type": "p",
      "text": "Jovere Collective S.L. is responsible for operating the AIRfasting platform, including software development, platform maintenance, customer support, subscription management, security, and acting as the primary data controller for personal data processed through AIRfasting."
    },
    {
      "type": "p",
      "text": "AIRfasting is financially supported by an investor holding company and collaborates with a strategic wellness partner that contributes fasting methodologies and educational content. Details of how these parties relate to your personal data are set out in our Privacy Policy."
    },
    {
      "type": "h1",
      "text": "3. Eligibility"
    },
    {
      "type": "p",
      "text": "AIRfasting is intended for adults aged 18 years or older. By using AIRfasting, you confirm that you are at least 18 years old and legally capable of entering into a binding contract. AIRfasting is not designed for, and should not be used by, children."
    },
    {
      "type": "p",
      "text": "If we become aware that a user does not meet this eligibility requirement, we may suspend or terminate their account."
    },
    {
      "type": "h1",
      "text": "4. The Service"
    },
    {
      "type": "p",
      "text": "AIRfasting is a wellness platform that allows you to:"
    },
    {
      "type": "ul",
      "items": [
        "create and manage an account;",
        "plan fasting schedules using menstrual cycle-based planning, or alternative lunar-phase planning if you prefer not to track menstruation;",
        "track fasting history and wellness trends;",
        "receive reminders and educational content;",
        "subscribe to premium features."
      ]
    },
    {
      "type": "p",
      "text": "AIRfasting is a wellness and educational tool. AIRfasting is not a medical device, a healthcare provider, a diagnostic tool, or a substitute for professional medical advice. See our Health & Wellness Disclaimer for full details."
    },
    {
      "type": "h1",
      "text": "5. Accounts"
    },
    {
      "type": "h2",
      "text": "5.1 Registration"
    },
    {
      "type": "p",
      "text": "To use most features of AIRfasting, you must create an account and provide accurate, current information. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account."
    },
    {
      "type": "h2",
      "text": "5.2 Accuracy"
    },
    {
      "type": "p",
      "text": "You agree to keep your account information accurate and up to date. Wellness insights and fasting plans generated by AIRfasting depend on the accuracy of the information you provide."
    },
    {
      "type": "h2",
      "text": "5.3 Account Security"
    },
    {
      "type": "p",
      "text": "Notify us promptly at support@airfasting.com if you suspect unauthorized use of your account."
    },
    {
      "type": "h1",
      "text": "6. Subscriptions, Trials, and Payment"
    },
    {
      "type": "h2",
      "text": "6.1 Free Trial"
    },
    {
      "type": "p",
      "text": "AIRfasting offers a 30-day free trial. A valid payment card is required to begin the trial."
    },
    {
      "type": "h2",
      "text": "6.2 Automatic Conversion and Renewal"
    },
    {
      "type": "p",
      "text": "Unless you cancel before the trial period ends, your account will automatically convert to a paid subscription, and the applicable subscription fee will be charged to your payment method. Subscriptions renew automatically at the end of each billing period unless cancelled."
    },
    {
      "type": "h2",
      "text": "6.3 Cancellation"
    },
    {
      "type": "p",
      "text": "You may cancel your subscription at any time through your account settings or by contacting us. Cancellation will take effect at the end of the current billing period. You will retain access to premium features until that date."
    },
    {
      "type": "h2",
      "text": "6.4 Effect of Cancellation or Expiry"
    },
    {
      "type": "p",
      "text": "Once premium access ends, certain features will no longer be available. Your historical fasting and wellness records will remain available to you in a limited, read-only state, unless you request deletion of your data in accordance with our Privacy Policy."
    },
    {
      "type": "h2",
      "text": "6.5 Payment Processing"
    },
    {
      "type": "p",
      "text": "Payments are processed by our third-party payment processor, Stripe. We do not store your full payment card details. See our Privacy Policy and Subprocessor Register for details."
    },
    {
      "type": "h2",
      "text": "6.6 Price Changes"
    },
    {
      "type": "p",
      "text": "We may change subscription pricing from time to time. We will provide advance notice before any price change affecting your renewal."
    },
    {
      "type": "h2",
      "text": "6.7 Refunds"
    },
    {
      "type": "p",
      "text": "Refunds, where applicable, will be handled in accordance with applicable Spanish and EU consumer protection law, including your statutory right of withdrawal for digital services, as further described at checkout."
    },
    {
      "type": "h1",
      "text": "7. Acceptable Use"
    },
    {
      "type": "p",
      "text": "You agree not to:"
    },
    {
      "type": "ul",
      "items": [
        "use AIRfasting for any unlawful purpose or in violation of these Terms;",
        "attempt to gain unauthorized access to AIRfasting's systems or other users' accounts;",
        "reverse engineer, decompile, or attempt to extract the source code of AIRfasting, except as permitted by law;",
        "use automated means (bots, scrapers) to access AIRfasting without our written permission;",
        "upload harmful code or attempt to disrupt the Service;",
        "misrepresent your identity or impersonate another person;"
      ]
    },
    {
      "type": "p",
      "text": "We reserve the right to suspend or terminate accounts that violate this section."
    },
    {
      "type": "h1",
      "text": "8. Health & Wellness Disclaimer (Summary)"
    },
    {
      "type": "p",
      "text": "AIRfasting is not a medical device, healthcare provider, physician, dietitian, treatment program, or diagnostic tool. Fasting may not be appropriate for everyone. You should consult a healthcare professional before beginning any fasting plan, particularly if you are pregnant, breastfeeding, trying to conceive, living with diabetes, an eating disorder, cardiovascular disease, an endocrine disorder, or taking medication that may be affected by fasting."
    },
    {
      "type": "p",
      "text": "You are solely responsible for decisions about your health, and AIRfasting's content does not replace professional medical judgment. The full disclaimer is set out in our Health & Wellness Disclaimer, which is incorporated into these Terms."
    },
    {
      "type": "h1",
      "text": "9. Intellectual Property"
    },
    {
      "type": "p",
      "text": "AIRfasting's software, design, trademarks, educational content, and underlying technology are owned by or licensed to Jovere Collective S.L. and its partners. Nothing in these Terms transfers any intellectual property rights to you, except a limited, non-exclusive, non-transferable, revocable license to use AIRfasting for its intended personal, non-commercial wellness purposes."
    },
    {
      "type": "p",
      "text": "We do not claim ownership of the personal data or health information you input into AIRfasting. See our Privacy Policy for how your data is handled."
    },
    {
      "type": "h1",
      "text": "10. Your Content"
    },
    {
      "type": "p",
      "text": "You retain rights over any information, notes, or content you submit to AIRfasting (\"User Content\"). You grant Jovere Collective S.L. a limited license to process User Content solely to operate, maintain, and improve the Service, in accordance with our Privacy Policy."
    },
    {
      "type": "h1",
      "text": "11. Disclaimers"
    },
    {
      "type": "p",
      "text": "To the fullest extent permitted by applicable law:"
    },
    {
      "type": "ul",
      "items": [
        "AIRfasting is provided \"as is\" and \"as available,\" without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement.",
        "We do not guarantee that AIRfasting will be uninterrupted, error-free, or free of harmful components.",
        "Educational content is provided for general wellness purposes and may not be accurate, complete, or applicable to your individual circumstances."
      ]
    },
    {
      "type": "p",
      "text": "Nothing in these Terms limits any statutory rights you have as a consumer under Spanish or EU law that cannot lawfully be excluded."
    },
    {
      "type": "h1",
      "text": "12. Limitation of Liability"
    },
    {
      "type": "p",
      "text": "To the fullest extent permitted by applicable law, Jovere Collective S.L. shall not be liable for indirect, incidental, special, consequential, or punitive damages, or loss of data, arising from your use of AIRfasting."
    },
    {
      "type": "p",
      "text": "Nothing in these Terms excludes or limits liability for death or personal injury caused by negligence, fraud, or any liability that cannot lawfully be excluded under Spanish or EU consumer protection law."
    },
    {
      "type": "h1",
      "text": "13. Termination"
    },
    {
      "type": "p",
      "text": "You may stop using AIRfasting and close your account at any time. We may suspend or terminate your access to AIRfasting if you breach these Terms, subject to applicable law. Upon termination, provisions that by their nature should survive (including Sections 9–16) will continue to apply."
    },
    {
      "type": "h1",
      "text": "14. Changes to These Terms"
    },
    {
      "type": "p",
      "text": "We may update these Terms from time to time to reflect changes in our Service, legal requirements, or business operations. We will notify you of material changes through the Service or by email in advance of them taking effect. Continued use of AIRfasting after changes take effect constitutes acceptance of the updated Terms."
    },
    {
      "type": "h1",
      "text": "15. Governing Law and Jurisdiction"
    },
    {
      "type": "p",
      "text": "These Terms are governed by the laws of Spain, without prejudice to any mandatory consumer protection rules of your country of residence if you are a consumer within the EU. Any disputes will be subject to the jurisdiction of the competent courts of Spain, without prejudice to your right as a consumer to bring proceedings in the courts of your own EU member state of residence, and to your right to use the EU Online Dispute Resolution platform."
    },
    {
      "type": "h1",
      "text": "16. Contact Us"
    },
    {
      "type": "p",
      "text": "If you have questions about these Terms, please contact us at:"
    },
    {
      "type": "p",
      "text": "Jovere Collective S.L."
    },
    {
      "type": "p",
      "text": "Calle Quevedo, Núm. 16, 03700 Dénia (Alicante), Spain"
    },
    {
      "type": "p",
      "text": "support@airfasting.com"
    },
    {
      "type": "note",
      "text": "This document is part of AIRfasting's Legal Framework and should be read together with the Privacy Policy, Cookie Policy, Health & Wellness Disclaimer."
    }
  ]
};
